### PR TITLE
fix: fix backreferencing issue for digits greater than 10

### LINKED ISSUE #38: [BUG]: Cannot handle references with value greater than 10
If I have an expression `/...\10/` the reference will be parsed as '1' rather than '10'. This is confirmed by the fact that [here](https://github.com/fent/ret.js/blob/efb9f07070402962192277189e99f9b700c85b70/lib/tokenizer.ts#L73) only one digit is tested.

### PR DESCRIPTION
**Pull request by jeswr**
Closes #38 .

This solves the initial issue discussed in #38 , however, it does not yet resolve this [follow up](https://github.com/fent/ret.js/issues/38#issuecomment-1006460390) observation.

In fact this introduces a bug for patterns like `(a) - \11` as `\11` *should* be treated as a value since there is only one capturing group. I will leave this as a draft until this is resolved.

### CODE REVIEW

**Comment by fent** [comment]
> In fact this introduces a bug for patterns like `(a) - \11` as `\11` _should_ be treated as a value since there is only one capturing group. I will leave this as a draft until this is resolved.

i checked if you can reference a group before it shows up in the regex

image

so this literal value would have to be inserted post parsing since it needs to know how many groups exist

**Comment by jeswr** [comment]
> so this literal value would have to be inserted post parsing since it needs to know how many groups exist

This is a very good point/find - I have solved everything except this as of https://github.com/fent/ret.js/pull/39/commits/411b848c70c90b704ee0b8c940b5af222b1fc45c but cannot think of an elegant way to do this post processing right now (I accidentally staged a broken attempt at doing this in my most recent lint:fix commit but you can ignore this).

I don't have time to work on resolving this for the next couple of days - so if you want to take over or point me in a direction that you are thinking it would be appreciated :)

**Comment by jeswr** [comment]
Converting back to draft as I made another incorrect assumption about the behavior of capture groups - they are not scoped. I.e.you can reference outer capture groups from inside another one

image

File: lib/tokenizer.ts [hunk 1]
```diff
@@ -17,10 +17,12 @@ export const tokenizer = (regexpStr: string): Root => {
...
   let groupStack: (Group | Root)[] = [];
 
+  let referenceQueue: Reference[] = [];
+  let groupCount = 0;
+
   const repeatErr = (col: number) => {
     throw new SyntaxError(
-      `Invalid regular expression: /${
-        regexpStr
+      `Invalid regular expression: /${regexpStr
```
Comment (fent) [inline lib/tokenizer.ts:25]: this PR has many small stylistic changes like this. were these auto formatted? i ran the `lint:fix` script but it didn't generate these changes. even so, let's try to keep this PR's changes related to only the PR's purpose. otherwise, it is harder to read

**Review by fent — CHANGES_REQUESTED** [review]

File: lib/tokenizer.ts (hunk 1 above)
Comment (jeswr) [reply lib/tokenizer.ts]: This was probably the prettier extension I have in vscode. I have now reverted these formatting changes :)

File: lib/tokenizer.ts [hunk 2]
```diff
@@ -154,6 +168,8 @@ export const tokenizer = (regexpStr: string): Root => {
           }
 
           group.remember = false;
+        } else {
+          groupCount += 1;
```
Comment (fent) [inline lib/tokenizer.ts:172]: oh i hadn't realized they can't be referenced if they're special group types. cool

**Review by fent — APPROVED** [review]

**Comment by fent** [comment]
thanks for the fix! learned some new things about javascript regex :o

**Review by fent — CHANGES_REQUESTED** [review]
wait! i was just looking at https://github.com/fent/ret.js/issues/31

the escaped code points only match octal numbers, so

    /\18/ // Match code point 1, followed by "8"

**Comment by jeswr** [comment]
> wait! i was just looking at #31
> 
> the escaped code points only match octal numbers, so
> 
> ```
> /\18/ // Match code point 1, followed by "8"
> ```

Unless I'm misinterpreting, this is not correct (at least in firefox)

image

**Comment by fent** [comment]
> Ahh so this should be tokenized as
> 
> ```ts
> {
> type: types.CHAR,
> value: 1
> },
> {
> type: types.CHAR,
> value: '8'.charCodeAt(0)
> }
> ```

right, makes the `updateReferences` function a bit more complicated. the detection and separation part not so much, but inserting an additional token next to that one is

File: lib/tokenizer.ts [hunk 3]
```diff
@@ -295,5 +313,49 @@ export const tokenizer = (regexpStr: string): Root => {
...
+  for (const elem of referenceQueue.reverse()) {
+    if (groupCount < elem.reference.value) {
+      // If there is nothing to reference then turn this into a char token
+      elem.reference.type = types.CHAR;
+
+      const valueString = elem.reference.value.toString();
+      // If the number is not octal then we need to create multiple tokens
+      // https://github.com/fent/ret.js/pull/39#issuecomment-1008229226
+      if (!/^[0-7]+$/.test(valueString)) {
+        const val = parseInt(valueString[0], 10);
```
Comment (fent) [inline lib/tokenizer.ts:343]: i don't think the separation occurs only at the 0th position

image

File: lib/tokenizer.ts [hunk 4]
```diff
@@ -295,5 +313,49 @@ export const tokenizer = (regexpStr: string): Root => {
...
+        elem.reference.value = val > 7 ? valueString.charCodeAt(0) : val;
+
+        if (valueString.length > 1) {
+          const tail = elem.stack.splice(elem.index + 1);
+
+          // eslint-disable-next-line max-depth
```
Comment (fent) [inline lib/tokenizer.ts:349]: i think we can remove this rule instead. too inconvenient sometimes. what do you think?

**Review by fent — CHANGES_REQUESTED** [review]

File: lib/tokenizer.ts (hunk 3 above)
Comment (jeswr) [reply lib/tokenizer.ts]: I *think* this has been addressed properly now

File: test/main-test.js [hunk 5]
```diff
@@ -465,6 +465,310 @@ vows.describe('Regexp Tokenizer')
...
+        topic: ret('\\2'),
+        'Tokenizes correctly': t => {
+          assert.deepStrictEqual(t, {
+            type: types.ROOT, stack: [
+              { type: types.CHAR, value: 2 },
+            ],
+          });
+        },
+      },
+      '\\9': {
```
Comment (fent) [inline test/main-test.js:760]: i would add an additional test for `'\\90'`, should tokenize as `[char('9'), char('0')`

**Review by fent — CHANGES_REQUESTED** [review]
finally looking at this. added a couple of comments on tests. otherwise, the logic looks good!

**Comment by jeswr** [comment]
> finally looking at this. added a couple of comments on tests. otherwise, the logic looks good!

Added those changes - should be ready to merge now

**Review by fent — APPROVED** [review]

**Comment by fent** [comment]
thanks again!
